services:
  - type: web
    name: conversor-pdf
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    envVars:
      - key: PORT
        value: "10000"
    autoDeploy: true
